# Generated by Django 5.0.3 on 2024-03-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_antecedentes', '0001_initial'),
        ('crear_persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedente',
            name='usuarioRegistrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antecedente',
            name='certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.certificado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_persona.pais'),
        ),
        migrations.AddField(
            model_name='antecedente',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.departamento'),
        ),
        migrations.AddField(
            model_name='antecedente',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.distrito'),
        ),
        migrations.AddField(
            model_name='historialcertificado',
            name='duenno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_persona.persona'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.historialcertificado'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.departamento'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.provincia'),
        ),
        migrations.AddField(
            model_name='antecedente',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.provincia'),
        ),
        migrations.AddField(
            model_name='antecedente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.tipoantecedente'),
        ),
        migrations.AddField(
            model_name='historialcertificado',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.tipocertificado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.tipocertificado'),
        ),
    ]
